print('\nTabuada.')
di = float(input('Digite o numero aqui: '))
print('\n+++++++++++SOMA DE {}++++++++++++'.format(di))
print('{} + 1 = {}\n{} + 2 = {}\n{} + 3 = {}'.format(di, di + 1, di, di + 2, di, di + 3))
print('{} + 4 = {}\n{} + 5 = {}\n{} + 6 = {}'.format(di, di + 4, di, di + 5, di, di + 6))
print('{} + 7 = {}\n{} + 8 = {}\n{} + 9 = {}\n{} + 10 = {}'.format(di ,di + 7, di ,di + 8, di, di + 9, di , di + 10))
print('\n---------SUBTRAÇAÕ DE {}----------'.format(di))
print('{} - 1 = {}\n{} - 2 = {}\n{} - 3 = {}'.format(di , di - 1, di, di - 2, di, di - 3))
print('{} - 4 = {}\n{} - 5 = {}\n{} - 6 = {}'.format(di , di - 4, di, di - 5, di, di - 6))
print('{} - 7 = {}\n{} - 8 = {}\n{} - 9 = {}\n{} - 10 = {}'.format(di, di - 7, di, di - 8, di, di - 9, di, di - 10 ))
print('\nxxxxxxxMULTIPLICAÇAÕ DE {}xxxxxxxxx'.format(di))
print('{} x 1 = {}\n{} x 2 = {}\n{} x 3 = {}'.format(di, di * 1, di, di * 2, di, di * 3))
print('{} x 4 = {}\n{} x 5 = {}\n{} x 6 = {}'.format(di, di * 4, di, di * 5, di, di * 6))
print('{} x 7 = {}\n{} x 8 = {}\n{} x 9 = {}\n{} x 10 = {}'.format(di, di * 7, di, di * 8, di, di * 9, di, di * 10))
print('\n////////////Divisaõ DE {}///////////'.format(di))
print('{} / 1 = {:.1f}\n{} / 2 = {:.1f}\n{} / 3 = {:.1f}'.format(di, di / 1, di, di / 2, di, di / 3))
print('{} / 4 = {:.1f}\n{} / 5 = {:.1f}\n{} / 6 = {:.1f}'.format(di, di / 4, di, di / 5, di, di / 6))
print('{} / 7 = {:.1f}\n{} / 8 = {:.1f}\n{} / 9 = {:.1f}\n{} / 10 = {:.1f}'.format(di, di / 7, di, di / 8, di, di / 9, di, di / 10))
